language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-drupalbase' ]; then cd .. && eval "mv $currentfolder generator-drupalbase" && cd generator-drupalbase; fi

